config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  get 'habits/index' => 'habits#index'
  get 'habits/new' => "habits#new", as: :new_habit
  post 'habits' => 'habits#create'

  resources :habits do
    resources :journals
  end

end

app/models/habit.rb
class Habit < ActiveRecord::Base
  has_many :journals, dependent: :destroy
  validates :name, presence: true
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :habit
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController

  def index
    @habits = Habit.all
  end

  def new
    @habit = Habit.new
  end

  def show
    @habit = Habit.find(params[:id])
  end

  def create
    @habit = Habit.new(params.require(:habit).permit(:name, :mission_statement, :description, :frequency, :duration, :text))
    if @habit.save!
      redirect_to habits_path
    else
      render :new
    end
  end

  def destroy
    @habit = Habit.find(params[:id])
    @habit.destroy

    redirect_to habits_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def create
    @habit = Habit.find(params[:habit_id])
    @journal = @habit.journals.create(journal_params)
    redirect_to root_path
  end

  def destroy
    @habit = Habit.find(params[:habit_id])
    @journal = @habit.journals.create(journal_params)
    redirect_to habit_path(@habit)
  end

  private
  def journal_params
    params.require(:journal).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/habits/index.html.erb
<h1>Habits#index</h1>
  <div class='row'>
      <div class="col-md-4">
        <% @habits.each do |habit| %>
        <p>
          <strong>Habit</strong>
          <%= habit.name %></p>
        </p>

        <p>
          <strong>Why</strong>
          <%= habit.mission_statement %>
        </p>

        <p>
          <strong>Description</strong>
          <%= habit.description %>
        </p>


          <p> I will update my journal on this habit <%= habit.frequency %> </p>
          <p> The training will last for <%= habit.duration %> <% habit.frequency %>
              <% if habit.frequency == "daily" %>
                <%= "days." %>
              <% elsif habit.frequency == "weekly" %>
                <%= "weeks." %>
              <% else %>
                <%= "months." %>
              <% end %>
          </p>
        </div>
          <div class="col-md-4">
            <h4>Journal</h4>
            <% habit.journals.each do |journal| %>
              <p>
                <strong>Journal:</strong>
                <%= journal.body %>
              </p>
            <% end %>
            <h4>Update Journal</h4>
              <p><%= render partial: "journals/form", locals: {habit: habit} %></p>
              <p><%= link_to 'Delete', habit_path(habit), class:"btn btn-danger",
              method: :delete, data: { confirm: "Are you sure?" } %></p>
            <% end %>
          </div>
    <div class="col-md-4">
      <% @habits.each do |habit| %>
        <% if ((habit.journals.count.to_f / habit.duration.to_f) * 100).to_i < 100 %>
          <h4><%= habit.name %></h4>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100"
            style="width: <%= (habit.journals.count.to_f / habit.duration.to_f) * 100 %>%">
              <%= ((habit.journals.count.to_f / habit.duration.to_f) * 100).to_i %>%
            </div>
          </div>
        <% else %>
          <h3><i class="fa fa-check-square fa-lg"></i><%= habit.name %></h3>
        <% end %>
      <% end %>
      </div>
  </div>

app/views/habits/new.html.erb
<h1>Habits#new</h1>

<div class= "container">
  <%= simple_form_for @habit, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
    } do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, hint: "What new habit do you want to learn?" %>
  <%= f.input :mission_statement, as: :text, hint: "Why is it important to you?"%>
  <%= f.input :description, as: :text, hint: "Describe what your process will be" %>
  <%= f.input :frequency, collection: [:daily, :weekly, :monthly, ], label: "How often will you practice this new habit"%>
  <%= f.input :duration, collection: 1..31, hint: "How many days/weeks/months will it take to become a habit?" %>
  <%= f.submit %>
  <% end %>
</div>

app/views/habits/show.html.erb
<p>
  <strong>Title</strong>
  <%= @habit.name %>
</p>

<p>
  <strong>Text</strong>
  <%= @habit.description %>
</p>

<p>
  <strong>Journal:</strong>
  <%= render @habit.journals %>
</p>

app/views/home/index.html.erb
<div class="jumbotron center">
  <h1>Welcome to KataWay</h1>
    <div class="container">
      <%= link_to "Sign Up", "#", class: "btn btn-primary" %>
      <%= link_to "Log in", "#", class: "btn btn-default" %>
    </div>
</div>

app/views/journals/_form.html.erb
<%= simple_form_for([habit, habit.journals.build]) do |f| %>
  <%= f.text_area :body, label: "Journal" %>
  <%= f.submit %>


<% end %>

app/views/journals/_journal.html.erb
<p>
  <strong>Journal:</strong>
  <%= journal.body %>
</p>

<p>
  <%= link_to 'Delete Journal Entry', [journal.habit, journal],
  method: :delete,
  data: { confirm: 'Are you sure?'} %>
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">KataWay</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class= "container">
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>

    <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to 'Login', new_user_session_path %>
    <% end %>
    <%= link_to "Create New Habit", new_habit_path, class: "btn" %>
  </div>
<%= yield %>

</body>
</html>